[package]
name = "copy-images-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
regex = "1.5.5"
chrono = "0.4.38"
indicatif = "0.17.8"
clap = { version = "4.5.8", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10.1"
insta = "1.39.0"
