name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Build
      run: cargo build --verbose

    - name: Run tests and generate coverage report
      run: cargo llvm-cov --json --output-path coverage/llvm-cov.json

    - name: Upload code coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/llvm-cov.json
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        flags: unittests